Add initial rails configuration.
karlcloudy/my-sms pull request #1
Opened 2021-03-26 05:24 UTC by karlcloudy

## Description
Initial Rails and Docker configuration added to the mySMS project.

## Breakdown of Commits
Commit 1 : 74a940f85ea839fc07610144c047c474fc0a1441
- Added initial rails structure & configuration.
- Added Docker configuration for running app.

#### TODO Checklist
* [X] create a personal GitHub repo
* [X] create a develop branch and set as the Base branch of the repo
* [X] clone repo locally
* [X] create first feature branch task_1_add_initial_rails_config
* [X] add the base Rails app files, commit and push
* [X] add docker setup (if applicable)

2021-03-29 23:37 UTC, Luke-kb commented on Gemfile
> +gem 'mysql2', '~> 0.3.10'
might be best to use version 0.3.20 as that is the version that JRPlus uses

2021-03-29 23:39 UTC, Luke-kb requested changes
Just one comment re gemfile, but other than that looks good 👍

2021-03-30 00:13 UTC, karlcloudy commented on Gemfile
> +gem 'mysql2', '~> 0.3.10'
Discussed in Slack - version that is being used by rb here is 0.3.21 (Plus has the version specified as _exactly_ 0.3.20 as mentioned). Decided that as patch releases are supposed to be backwards compatible with code targeting previous patch levels of the same major.minor version, that we'll keep it this way unless problems are uncovered in the future.

2021-03-30 00:14 UTC, Luke-kb approved these changes
+1 👍

2021-03-30 00:17 UTC, merged