Task 2 add student model
karlcloudy/my-sms pull request #2
Opened 2021-03-31 05:58 UTC by karlcloudy

## Description
Create the 'Student' model; and add the 'factory_bot_rails', and 'faker' gems to the project (demonstration below).

## Breakdown of Commits
Commit 1 : c5a7110
- Added Student model to project.
- Added factory_bot_rails, and faker gems.
 
Commit 2 : d7db71e 
- Added more columns to `create_student` migration.
- Fixed issue preventing `db:migrate` working on MySQL database.

#### TODO Checklist
* [X] Create student model with attributes: title, first_name, middle_name, last_name, email, birth_date, gender.
* [X] Add factory_bot_rails gem and display some example usage in the PR description.
* [X] add the faker gem and demonstrate usage in PR description.

  
#### factory_bot_rails usage
FactoryBot can be used to generate data for testing purposes.

NOTE: The example below is based on the example shown on the github repo for the factory_bot project, adapted for producing Student test data (https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md)
```rb
FactoryBot.define do
    factory :student do
        #Use plausible information for a Student.
        title { "Mr" }
        first_name { "Henry" }
        middle_name { "Johnathon" }
        last_name { "Ford" }
        gender { "M" }
        birth_date { "02031901" }
        email { "henryjford@example.org" }
    end
end
```

### faker usage
Faker allows the generation of convincing, but fake data. Combined with FactoryBot, you could seed multiple records with random information. It is possible to seed Faker to produce the same sequence of fake data every time if this is desirable.

The below example is based on the above, but with Faker used to generate the information instead. This will generate different information each time it is used.
```rb
FactoryBot.define do
    factory :student do
        #Generate student information via Faker instead.
        title { Faker::Name.prefix }
        first_name { Faker::Name.first_name }
        middle_name { Faker::Name.middle_name }
        last_name { Faker::Name.last_name }
        gender { Faker::Gender.binary_type[0] } #short_binary_type seems unavailable in my version, so I took the first character of binary_type instead
        birth_date { Faker::Date.birthday(min_age: 13, max_age: 100) }
        email { Faker::Internet.safe_email }
    end
end
```

2021-03-31 21:26 UTC, jbat commented on test/unit/student_test.rb
> +require 'test_helper'
ReadyTech rails apps prefer RSpec over test-unit.
can remove this test

2021-03-31 21:33 UTC, jbat commented on test/fixtures/students.yml
> +  gender: MyString
@karlcloudy this file can be removed and essentially replaced with a factory for the student model as per you PR description.  A fixture is used to easily create test data but has pretty limited capabilities.

A factory however has a large set of features we can use so provide a lot more in terms of options for creating test data.

Add your students factory into a new directory spec/factories 
./spec/factories/students.rb

2021-03-31 21:36 UTC, jbat requested changes
@karlcloudy  looking good .. left a few comments

2021-03-31 23:59 UTC, karlcloudy commented on Gemfile
> +  gem 'test-unit'
If I recall I added 'test-unit' as a command I was running complained the gem was missing. I'll remove it.

2021-04-01 00:00 UTC, karlcloudy commented on test/fixtures/students.yml
> +  gender: MyString
Yep - will remove.

2021-04-01 00:24 UTC, jhuizy commented on db/migrate/20210330225119_create_students.rb
> +      t.string :gender, null: false, limit: 1 #'M', 'F', or 'O' for Male, Female, and Other respectively. Rails 3.x doesn't support enums, or I'd have used those :(
I think your solution is fine, but another approach could be to make it an integer and have constants defined for each enum value, eg.

```ruby
class Student < ActiveRecord::Model
  MALE = 0
  FEMALE = 1
  OTHER = 2

  # then you can define the methods that rails `enum` helper normally generates for you

  # returns true if the gender is male
  def male?
    gender == MALE
  end

  # sets the gender to male
  def male!
    gender = MALE
  end
```

That said, it's probably safest to represent _gender_ as a free text string (ie. storing "Female" instead of "F") or reference table. 
As an aside, if we were modelling _sex_, turns out there's an [ISO standard](https://en.wikipedia.org/wiki/ISO/IEC_5218) for what the constants could be

2021-04-01 00:34 UTC, karlcloudy commented on db/migrate/20210330225119_create_students.rb
> +      t.string :gender, null: false, limit: 1 #'M', 'F', or 'O' for Male, Female, and Other respectively. Rails 3.x doesn't support enums, or I'd have used those :(
Yeah, my thinking around having just the three categories with the single letter was down to AVETMISS handling this in a similar manner.

I notice your example inherits from `ActiveRecord::Model` as opposed to `ActiveRecord::Base` which mine does - just to be clear, I assume this isn't relevant in this example?

2021-04-01 00:41 UTC, jhuizy commented on db/migrate/20210330225119_create_students.rb
> +      t.string :gender, null: false, limit: 1 #'M', 'F', or 'O' for Male, Female, and Other respectively. Rails 3.x doesn't support enums, or I'd have used those :(
Ah yep sorry, you are correct it should be `ActiveRecord::Base` , just a typo 👍 

In regards to the avetmiss stuff, I generally prefer to have integer as it feels nicer to match on (rather than string values). And the representation (whether that be the UI displaying "Male" or AVETMISS displaying "M") should not be concerned with how its stored in the DB, as long as we can get from the DB representation to whatever UI representation we need.

Happy to approve as is though, just leaving my thoughts on it 👍

2021-04-01 02:51 UTC, jhuizy commented on config/initializers/abstract_mysql2_adapter.rb
> +  NATIVE_DATABASE_TYPES[:primary_key] = "int(11) auto_increment PRIMARY KEY" #We need this for db:migrate to be able to create tables properly in MySQL, or it complains about primary keys being nulla
Nice 👍

2021-04-01 02:52 UTC, jhuizy approved these changes
All looks good to me 👍

2021-04-01 02:55 UTC, karlcloudy commented on Gemfile
> +  gem 'test-unit'
Have since re-added - rails console was what required it and it's apparently a known bug. Included a comment in the Gemfile explaining its purpose in there.

2021-04-01 02:56 UTC, merged